/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#785c23",
        "on-primary-fixed": "#40000f",
        "secondary": "#765a21",
        "outline-variant": "#dac0c1",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#adcebe",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#8baa9b",
        "surface-container-highest": "#e7e2da",
        "tertiary-fixed": "#c9ead9",
        "outline": "#877273",
        "primary-fixed": "#ffdadb",
        "inverse-surface": "#32302b",
        "inverse-primary": "#ffb2b8",
        "on-primary-container": "#ef848f",
        "on-primary-fixed-variant": "#7c2a36",
        "secondary-fixed": "#ffdea4",
        "on-error": "#ffffff",
        "on-secondary-fixed": "#261900",
        "background": "#fef9f1",
        "on-surface-variant": "#554243",
        "surface-container-low": "#f8f3eb",
        "primary": "#4d0516",
        "secondary-fixed-dim": "#e6c17e",
        "surface-container-high": "#ece8e0",
        "surface-tint": "#9a414d",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#304d40",
        "surface-variant": "#e7e2da",
        "surface-bright": "#fef9f1",
        "on-secondary-fixed-variant": "#5b4309",
        "on-surface": "#1d1c17",
        "on-background": "#1d1c17",
        "primary-fixed-dim": "#ffb2b8",
        "on-tertiary-fixed": "#022016",
        "surface": "#fef9f1",
        "inverse-on-surface": "#f5f0e8",
        "on-error-container": "#93000a",
        "secondary-container": "#fed892",
        "tertiary": "#0b291f",
        "surface-container": "#f2ede5",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-dim": "#ded9d2",
        "primary-container": "#6b1d2a",
        "error": "#ba1a1a",
        "tertiary-container": "#223f33"
      },
      fontFamily: {
        "headline": ["DM Serif Display", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "serif": ["Newsreader", "serif"],
        "mono": ["DM Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
