/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "accent-burgundy": "var(--md-accent-burgundy)",
        "accent-gold": "var(--md-accent-gold)",
        "background": "var(--md-background)",
        "error": "var(--md-error)",
        "error-container": "var(--md-error-container)",
        "inverse-on-surface": "var(--md-inverse-on-surface)",
        "inverse-primary": "var(--md-inverse-primary)",
        "inverse-surface": "var(--md-inverse-surface)",
        "on-background": "var(--md-on-background)",
        "on-error": "var(--md-on-error)",
        "on-error-container": "var(--md-on-error-container)",
        "on-primary": "var(--md-on-primary)",
        "on-primary-container": "var(--md-on-primary-container)",
        "on-primary-fixed": "var(--md-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant)",
        "on-secondary": "var(--md-on-secondary)",
        "on-secondary-container": "var(--md-on-secondary-container)",
        "on-secondary-fixed": "var(--md-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant)",
        "on-surface": "var(--md-on-surface)",
        "on-surface-variant": "var(--md-on-surface-variant)",
        "on-tertiary": "var(--md-on-tertiary)",
        "on-tertiary-container": "var(--md-on-tertiary-container)",
        "on-tertiary-fixed": "var(--md-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--md-on-tertiary-fixed-variant)",
        "outline": "var(--md-outline)",
        "outline-variant": "var(--md-outline-variant)",
        "primary": "var(--md-primary)",
        "primary-container": "var(--md-primary-container)",
        "primary-fixed": "var(--md-primary-fixed)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim)",
        "secondary": "var(--md-secondary)",
        "secondary-container": "var(--md-secondary-container)",
        "secondary-fixed": "var(--md-secondary-fixed)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim)",
        "surface": "var(--md-surface)",
        "surface-bright": "var(--md-surface-bright)",
        "surface-container": "var(--md-surface-container)",
        "surface-container-high": "var(--md-surface-container-high)",
        "surface-container-highest": "var(--md-surface-container-highest)",
        "surface-container-low": "var(--md-surface-container-low)",
        "surface-container-lowest": "var(--md-surface-container-lowest)",
        "surface-dim": "var(--md-surface-dim)",
        "surface-tint": "var(--md-surface-tint)",
        "surface-variant": "var(--md-surface-variant)",
        "tertiary": "var(--md-tertiary)",
        "tertiary-container": "var(--md-tertiary-container)",
        "tertiary-fixed": "var(--md-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim)",
      },
      fontFamily: {
        "headline": ["DM Serif Display", "serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "serif": ["Newsreader", "serif"],
        "mono": ["DM Mono", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
